name: Continuous Integration

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test_compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install compiler
        run: sudo apt install gcc
      - name: compile test
        run: ./compile.sh
